### PR TITLE
Move NodeUA to backend section

### PR DESCRIPTION
**Pull request by JekRock**
### Contributor's Checklist:

- [x] **I have read and understood the [contribution rules](https://github.com/nikit0ns/Ukrainian_IT_Communities/blob/master/CONTRIBUTING.md). My submission complies with these rules.**
- [x] **My submission is grammatically correct.**

### CODE REVIEW

**Comment by JekRock** [comment]
@nikit0ns could you please clarify why this PR was closed?

**Comment by nikit0ns** [comment]
> @nikit0ns could you please clarify why this PR was closed?

Because I don't see the point of changing the category for this chat

**Comment by JekRock** [comment]
Thank you for sharing your intentions.
Maybe I should've shared mine first.

This group is focused mainly on the nodejs backend development, not frontend. So seeing it in the frontend section is a bit confusing.

**Comment by nikit0ns** [comment]
> Thank you for sharing your intentions. Maybe I should've shared mine first.
> 
> This group is focused mainly on the nodejs backend development, not frontend. So seeing it in the frontend section is a bit confusing.

Text me on the Telegram

**Pull request closed without merging**
